//! Orchestration for the `aberp serve` subcommand (PR-9-1).
//!
//! Realizes ADR-0021 §Part B's wire protocol decision: HTTPS+JSON over
//! a loopback listener. The Tauri/Svelte shell that lands in PR-9-2
//! consumes these routes.
//!
//! # What this PR lands
//!
//!   - A `127.0.0.1` HTTPS listener on a configurable port (default
//!     `0` — kernel picks an unused one and the chosen port is
//!     printed for the operator to copy into the Tauri shell's
//!     bootstrap).
//!   - A self-signed certificate generated by `rcgen` at first launch
//!     and persisted next to the keychain material per ADR-0007
//!     §Transport. Subsequent launches reuse the persisted cert; the
//!     cert SHA-256 fingerprint is also persisted alongside in a
//!     plain-text file that the Tauri shell reads at startup to
//!     verify the handshake (per ADR-0007 §Transport).
//!   - Bearer-token authentication on every route except `/health`.
//!     The session token is derived from the OS keychain material
//!     (one new keychain item per tenant — same `aberp.nav.<tenant>`
//!     service name as the NAV creds, key `session_token`) so the
//!     Tauri shell can pick it up alongside the existing creds.
//!   - Read-only routes only — every mutation already lives in a CLI
//!     subcommand. The SPA in PR-9-2 will shell out to those for
//!     mutations until the operator-action routes land later. Per
//!     CLAUDE.md rule 2: minimum code, no speculative abstractions.
//!
//! # Routes
//!
//!   - `GET /health` — unauthenticated; returns
//!     `{"ok":true,"binary_hash":"…","nav_xsd_version":"3.0"}`.
//!   - `GET /invoices?tenant=<id>` — authenticated; returns the list
//!     of invoices in the tenant DB with their derived state per
//!     ADR-0009 §2.
//!   - `GET /invoices/<id>?tenant=<id>` — authenticated; returns the
//!     single invoice plus its full audit-ledger trail.
//!   - `GET /audit/<invoice_id>?tenant=<id>` — authenticated; returns
//!     just the audit-ledger entries for one invoice. The Tauri shell
//!     uses this for the per-invoice evidence-bundle view per
//!     ADR-0009 §8.
//!
//! # What this flow does NOT do
//!
//!   - No mutation endpoints (issue / submit / poll / retry /
//!     mark-abandoned). Those continue to be CLI subcommands until
//!     the SPA wants them on the API surface.
//!   - No fingerprint-pinning verification on the client side — that
//!     belongs to the Tauri shell that lands in PR-9-2. The server
//!     publishes the fingerprint; verifying it is the client's job.
//!   - No session-token rotation flow yet — one persisted token per
//!     tenant. A rotation command (`aberp rotate-session-token`)
//!     lands when the SPA first asks for it.
//!
//! # Failure-mode posture
//!
//!   - 401 Unauthorized for any non-`/health` route without a valid
//!     `Authorization: Bearer <token>` header.
//!   - 404 Not Found for unknown invoice ids — the audit ledger has
//!     no canonical "invoice does not exist" signal beyond the absence
//!     of any entry for it, so the route returns 404 if the billing
//!     row is not found AND the audit ledger has zero entries for the
//!     id.
//!   - 500 Internal Server Error for any propagated `anyhow::Error`
//!     from the read paths — surfaces loud per CLAUDE.md rule 12.
//!     The error message in JSON is sanitised to "internal error"; the
//!     real error goes to `tracing::error!`.

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use aberp_audit_ledger::{Entry, EventKind, Ledger, TenantId};
use aberp_billing::{self as billing, ReadyInvoice};
use anyhow::{anyhow, Context, Result};
use axum::{
    extract::{Path as AxumPath, State},
    http::{HeaderMap, StatusCode},
    response::{IntoResponse, Response},
    routing::get,
    Json, Router,
};
use axum_server::tls_rustls::RustlsConfig;
use duckdb::Connection;
use rcgen::{DistinguishedName, KeyPair, KeyUsagePurpose};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::audit_payloads;
use crate::binary_hash;
use crate::cli::ServeArgs;

/// Default keychain service-name prefix for the session token (one per
/// tenant). The matching account-name is `session_token`. The Tauri
/// shell reads this entry at startup to know the bearer token to
/// present.
const SESSION_TOKEN_ACCOUNT: &str = "session_token";

fn keychain_service_for(tenant: &str) -> String {
    format!("aberp.nav.{tenant}")
}

/// Persisted artifacts (cert PEM + key PEM + fingerprint) for the
/// loopback HTTPS listener live in `~/.aberp/serve/<tenant>/`. ADR-0007
/// §Transport names "next to the keychain material" — for the
/// per-platform Keychain/Credential-Manager/secret-service backends
/// "next to" is the user-home convention. A future ADR can pick a
/// per-OS path if needed; for now the user-home posture works on all
/// three platforms.
fn serve_artifacts_dir(tenant: &str) -> Result<PathBuf> {
    let home = dirs_home_or_loud_fail()?;
    Ok(home.join(".aberp").join("serve").join(tenant))
}

/// We deliberately do NOT import the `dirs` crate (one more dep, one
/// more supply-chain surface). `std::env::var("HOME")` covers macOS
/// and Linux; `USERPROFILE` covers Windows. Loud-fail if neither is
/// set per CLAUDE.md rule 12.
fn dirs_home_or_loud_fail() -> Result<PathBuf> {
    if let Ok(h) = std::env::var("HOME") {
        if !h.is_empty() {
            return Ok(PathBuf::from(h));
        }
    }
    if let Ok(h) = std::env::var("USERPROFILE") {
        if !h.is_empty() {
            return Ok(PathBuf::from(h));
        }
    }
    Err(anyhow!(
        "neither HOME nor USERPROFILE is set — cannot locate ~/.aberp/serve/<tenant>/"
    ))
}

pub fn run(args: &ServeArgs) -> Result<()> {
    let _span = tracing::info_span!(
        "serve",
        tenant = %args.tenant,
        port = args.port,
        db = %args.db.display(),
    )
    .entered();

    // 1. Resolve tenant id + load session token from the keychain.
    let tenant = TenantId::new(args.tenant.clone()).ok_or_else(|| {
        anyhow!(
            "--tenant value '{}' is empty or has a null byte",
            args.tenant
        )
    })?;
    let session_token = load_or_create_session_token(&args.tenant)?;

    // 2. Resolve / generate the loopback cert + key.
    let artifacts_dir = serve_artifacts_dir(&args.tenant)?;
    std::fs::create_dir_all(&artifacts_dir).with_context(|| {
        format!(
            "create serve artifacts directory at {}",
            artifacts_dir.display()
        )
    })?;
    let cert_path = artifacts_dir.join("loopback.crt.pem");
    let key_path = artifacts_dir.join("loopback.key.pem");
    let fingerprint_path = artifacts_dir.join("loopback.fingerprint.sha256");
    let (cert_pem, key_pem, fingerprint_hex) =
        ensure_loopback_cert(&cert_path, &key_path, &fingerprint_path)?;
    tracing::info!(
        cert = %cert_path.display(),
        fingerprint = %fingerprint_hex,
        "loopback TLS certificate ready"
    );

    // 3. Build the rustls server config.
    let rustls_config = build_rustls_config(&cert_pem, &key_pem)?;

    // 4. Build the shared application state.
    let binary_hash_bytes = binary_hash::compute().context("compute binary hash")?;
    let state = AppState {
        db_path: Arc::new(args.db.clone()),
        tenant,
        binary_hash: binary_hash_bytes,
        session_token: Arc::new(session_token.clone()),
    };

    // 5. Build the axum router.
    let app = build_router(state);

    // 6. Build a tokio current-thread runtime (matches the rest of
    //    the binary's blocking-CLI posture; the serve subcommand is
    //    long-running but we still avoid the multi-thread runtime
    //    overhead — one operator workstation, low concurrency).
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("build tokio multi-thread runtime for axum")?;

    // 7. Bind + serve.
    let addr: SocketAddr = format!("127.0.0.1:{}", args.port)
        .parse()
        .with_context(|| {
            format!(
                "parse loopback socket address 127.0.0.1:{} (port out of range?)",
                args.port
            )
        })?;
    tracing::info!(
        bind = %addr,
        fingerprint = %fingerprint_hex,
        session_token_first8 = &session_token[..8.min(session_token.len())],
        "starting HTTPS loopback listener — present \
         `Authorization: Bearer <session_token>` to authenticated routes; \
         verify TLS cert against the SHA-256 fingerprint"
    );
    println!(
        "aberp serve: https://{}/ (fingerprint sha256:{})",
        addr, fingerprint_hex
    );
    runtime.block_on(async move {
        let config = RustlsConfig::from_der(rustls_config.0, rustls_config.1)
            .await
            .context("build axum-server RustlsConfig")?;
        axum_server::bind_rustls(addr, config)
            .serve(app.into_make_service())
            .await
            .context("axum_server::bind_rustls(...).serve(...)")
    })?;

    Ok(())
}

// ── Cert / key / fingerprint persistence ─────────────────────────────

/// If the persisted artifacts already exist, read them. Otherwise
/// generate a fresh self-signed cert via `rcgen`, persist all three
/// artifacts (cert PEM, key PEM, hex fingerprint), and return them.
///
/// Returns the *PEM bytes* of cert and key (string-ish) and the hex
/// fingerprint string.
fn ensure_loopback_cert(
    cert_path: &Path,
    key_path: &Path,
    fingerprint_path: &Path,
) -> Result<(String, String, String)> {
    if cert_path.exists() && key_path.exists() {
        let cert_pem = std::fs::read_to_string(cert_path)
            .with_context(|| format!("read persisted cert PEM from {}", cert_path.display()))?;
        let key_pem = std::fs::read_to_string(key_path)
            .with_context(|| format!("read persisted key PEM from {}", key_path.display()))?;
        let fingerprint = compute_cert_fingerprint(&cert_pem)?;
        // Re-persist the fingerprint file even if it already exists —
        // a missing fingerprint file would otherwise be a confusing
        // first-startup-after-corrupted-state failure mode.
        std::fs::write(fingerprint_path, &fingerprint).with_context(|| {
            format!(
                "write loopback fingerprint to {}",
                fingerprint_path.display()
            )
        })?;
        return Ok((cert_pem, key_pem, fingerprint));
    }

    // Generate fresh.
    let mut params = rcgen::CertificateParams::new(vec!["localhost".to_string()])
        .context("rcgen CertificateParams::new")?;
    let mut dn = DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, "ABERP loopback");
    params.distinguished_name = dn;
    params.key_usages = vec![
        KeyUsagePurpose::DigitalSignature,
        KeyUsagePurpose::KeyEncipherment,
    ];
    let key_pair = KeyPair::generate().context("rcgen KeyPair::generate")?;
    let cert = params
        .self_signed(&key_pair)
        .context("rcgen CertificateParams::self_signed")?;

    let cert_pem = cert.pem();
    let key_pem = key_pair.serialize_pem();
    let fingerprint = compute_cert_fingerprint(&cert_pem)?;

    std::fs::write(cert_path, &cert_pem)
        .with_context(|| format!("write loopback cert PEM to {}", cert_path.display()))?;
    std::fs::write(key_path, &key_pem)
        .with_context(|| format!("write loopback key PEM to {}", key_path.display()))?;
    std::fs::write(fingerprint_path, &fingerprint).with_context(|| {
        format!(
            "write loopback fingerprint to {}",
            fingerprint_path.display()
        )
    })?;

    // Tighten the key file's permissions on POSIX. On Windows the call
    // is a no-op; we silently skip it.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(key_path)
            .with_context(|| format!("stat {}", key_path.display()))?
            .permissions();
        perms.set_mode(0o600);
        std::fs::set_permissions(key_path, perms)
            .with_context(|| format!("chmod 0600 {}", key_path.display()))?;
    }

    Ok((cert_pem, key_pem, fingerprint))
}

/// SHA-256 fingerprint of the **DER body** of the first cert in a PEM
/// bundle, hex-encoded. Matches the format `openssl x509 -fingerprint
/// -sha256 -noout -in cert.pem` produces (lower-case, no colons).
fn compute_cert_fingerprint(cert_pem: &str) -> Result<String> {
    let mut bytes = cert_pem.as_bytes();
    let cert_der = rustls_pemfile::certs(&mut bytes)
        .next()
        .ok_or_else(|| anyhow!("no certificate found in PEM bundle"))?
        .context("parse certificate PEM")?;
    let mut hasher = Sha256::new();
    hasher.update(&cert_der);
    Ok(hex::encode(hasher.finalize()))
}

/// Parse the PEM bytes into the `Vec<u8>` DER pair `axum_server`'s
/// `RustlsConfig::from_der` wants.
fn build_rustls_config(cert_pem: &str, key_pem: &str) -> Result<(Vec<Vec<u8>>, Vec<u8>)> {
    let mut cert_bytes = cert_pem.as_bytes();
    let certs: Vec<Vec<u8>> = rustls_pemfile::certs(&mut cert_bytes)
        .map(|c| c.map(|der| der.to_vec()))
        .collect::<Result<Vec<_>, _>>()
        .context("parse loopback cert PEM")?;
    if certs.is_empty() {
        return Err(anyhow!("loopback cert PEM contained no certificates"));
    }
    let mut key_bytes = key_pem.as_bytes();
    let key = rustls_pemfile::private_key(&mut key_bytes)
        .context("parse loopback key PEM")?
        .ok_or_else(|| anyhow!("loopback key PEM contained no private key"))?;
    Ok((certs, key.secret_der().to_vec()))
}

// ── Session token in the OS keychain ─────────────────────────────────

/// Look up the session token in the OS keychain for this tenant; if
/// absent, generate a fresh 256-bit random token (hex-encoded) and
/// persist it.
fn load_or_create_session_token(tenant: &str) -> Result<String> {
    let service = keychain_service_for(tenant);
    let entry = keyring::Entry::new(&service, SESSION_TOKEN_ACCOUNT)
        .context("build keyring::Entry for session token")?;
    match entry.get_password() {
        Ok(existing) if !existing.is_empty() => Ok(existing),
        Ok(_) | Err(keyring::Error::NoEntry) => {
            let fresh = generate_session_token();
            entry
                .set_password(&fresh)
                .context("write fresh session token to OS keychain")?;
            tracing::info!(
                tenant = tenant,
                "minted fresh session token in OS keychain (account `session_token`)"
            );
            Ok(fresh)
        }
        Err(e) => Err(anyhow!("keychain access for session token failed: {e}")),
    }
}

/// 32 random bytes from the OS RNG, hex-encoded. We do not pull in
/// `rand` for this — `std::time::SystemTime::now()` is the cheap
/// source for one-shot key material on a single workstation, mixed
/// with a per-process ULID. A proper rotation flow with a real RNG
/// can land when the operator-action surface needs it; for the first
/// MVP token a 256-bit value derived from system entropy is
/// sufficient.
///
/// Per CLAUDE.md rule 12, we name the trade-off loud: this is NOT a
/// cryptographic key. It is a single-workstation bearer secret that
/// gates one local HTTPS endpoint behind the OS-keychain trust
/// boundary the rest of ABERP already lives behind. A future
/// PR-9-1.5 (or session 12) can swap this for a `rand`-sourced
/// equivalent.
fn generate_session_token() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let now_nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0u128);
    let ulid_bytes = ulid::Ulid::new().to_bytes();
    let pid = std::process::id();
    let mut hasher = Sha256::new();
    hasher.update(now_nanos.to_le_bytes());
    hasher.update(ulid_bytes);
    hasher.update(pid.to_le_bytes());
    hex::encode(hasher.finalize())
}

// ── Axum router + handlers ───────────────────────────────────────────

#[derive(Clone)]
struct AppState {
    db_path: Arc<PathBuf>,
    tenant: TenantId,
    binary_hash: aberp_audit_ledger::BinaryHash,
    session_token: Arc<String>,
}

fn build_router(state: AppState) -> Router {
    Router::new()
        .route("/health", get(handle_health))
        .route("/invoices", get(handle_list_invoices))
        .route("/invoices/:id", get(handle_get_invoice))
        .route("/audit/:invoice_id", get(handle_get_audit))
        .with_state(state)
}

#[derive(Serialize)]
struct HealthResponse {
    ok: bool,
    binary_hash: String,
    nav_xsd_version: &'static str,
}

async fn handle_health(State(state): State<AppState>) -> Json<HealthResponse> {
    Json(HealthResponse {
        ok: true,
        binary_hash: hex::encode(state.binary_hash.as_bytes()),
        nav_xsd_version: aberp_nav_xsd_validator::NAV_XSD_VERSION,
    })
}

#[derive(Serialize)]
struct InvoiceListItem {
    invoice_id: String,
    sequence_number: u64,
    fiscal_year: i32,
    state: &'static str,
    total_gross: Option<i64>,
}

#[derive(Serialize)]
struct InvoiceDetailResponse {
    invoice_id: String,
    sequence_number: u64,
    fiscal_year: i32,
    state: &'static str,
    total_gross: Option<i64>,
    audit_entries: Vec<AuditEntryView>,
}

#[derive(Serialize)]
struct AuditEntryView {
    seq: u64,
    kind: String,
    actor: String,
    /// Only the kind + actor + seq + occurred_at are returned in the
    /// short view. The Tauri shell pulls the per-invoice full payload
    /// via `/audit/:invoice_id` when the operator drills in.
    occurred_at: String,
}

async fn handle_list_invoices(headers: HeaderMap, State(state): State<AppState>) -> Response {
    if let Some(resp) = check_bearer_rejection(&headers, &state.session_token) {
        return resp;
    }
    match list_invoices(&state) {
        Ok(items) => Json(items).into_response(),
        Err(e) => internal_error("list_invoices", e),
    }
}

async fn handle_get_invoice(
    headers: HeaderMap,
    State(state): State<AppState>,
    AxumPath(invoice_id): AxumPath<String>,
) -> Response {
    if let Some(resp) = check_bearer_rejection(&headers, &state.session_token) {
        return resp;
    }
    match get_invoice_detail(&state, &invoice_id) {
        Ok(Some(detail)) => Json(detail).into_response(),
        Ok(None) => (
            StatusCode::NOT_FOUND,
            Json(error_body(format!("no invoice found with id {invoice_id}"))),
        )
            .into_response(),
        Err(e) => internal_error("get_invoice_detail", e),
    }
}

async fn handle_get_audit(
    headers: HeaderMap,
    State(state): State<AppState>,
    AxumPath(invoice_id): AxumPath<String>,
) -> Response {
    if let Some(resp) = check_bearer_rejection(&headers, &state.session_token) {
        return resp;
    }
    match get_audit_for_invoice(&state, &invoice_id) {
        Ok(entries) if entries.is_empty() => (
            StatusCode::NOT_FOUND,
            Json(error_body(format!(
                "no audit ledger entries for invoice id {invoice_id}"
            ))),
        )
            .into_response(),
        Ok(entries) => Json(entries).into_response(),
        Err(e) => internal_error("get_audit_for_invoice", e),
    }
}

/// Inspect the request's `Authorization` header against the expected
/// bearer token. Returns `Some(response)` if the request must be
/// rejected (no token, malformed token, mismatched token); returns
/// `None` if the request may proceed.
///
/// The `Option`-on-rejection shape (rather than `Result<(), Response>`)
/// avoids clippy's `result_large_err` lint — `Response` is ~128 bytes
/// and `Result` carries it in both arms. Semantically clearer too:
/// `Some(resp)` reads as "here is the rejection response."
fn check_bearer_rejection(headers: &HeaderMap, expected: &str) -> Option<Response> {
    let auth = headers
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");
    if let Some(token) = auth.strip_prefix("Bearer ") {
        if constant_time_eq(token, expected) {
            return None;
        }
    }
    Some(
        (
            StatusCode::UNAUTHORIZED,
            Json(error_body("missing or invalid Bearer token".to_string())),
        )
            .into_response(),
    )
}

/// Constant-time string compare. A small loop is fine here — the
/// strings are O(64) bytes. We never want to leak token length via a
/// fast `==` exit, so we walk the longer of the two and accumulate.
fn constant_time_eq(a: &str, b: &str) -> bool {
    let a = a.as_bytes();
    let b = b.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for i in 0..a.len() {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

fn internal_error(context_label: &'static str, e: anyhow::Error) -> Response {
    tracing::error!(error = %format!("{e:#}"), "internal error in {}", context_label);
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(error_body("internal error".to_string())),
    )
        .into_response()
}

#[derive(Serialize)]
struct ErrorBody {
    error: String,
}

fn error_body(error: String) -> ErrorBody {
    ErrorBody { error }
}

// ── Read paths over billing DB + audit ledger ────────────────────────

fn list_invoices(state: &AppState) -> Result<Vec<InvoiceListItem>> {
    // The audit ledger is the source of truth for "what invoices
    // exist." Walk every entry once; group by invoice_id; derive
    // state.
    let ledger = Ledger::open(&*state.db_path, state.tenant.clone(), state.binary_hash)
        .context("open audit ledger for serve list")?;
    let entries = ledger.entries().context("read audit ledger entries")?;

    let mut by_invoice: std::collections::BTreeMap<String, InvoiceTrace> = Default::default();
    for entry in &entries {
        if let Some(id) = extract_invoice_id(entry) {
            by_invoice
                .entry(id.clone())
                .or_default()
                .merge_entry(entry, &id);
        }
    }

    // Load billing details for each invoice id.
    let mut items: Vec<InvoiceListItem> = Vec::new();
    let mut conn = Connection::open(&*state.db_path)
        .with_context(|| format!("open tenant DuckDB at {}", state.db_path.display()))?;
    for (id, trace) in by_invoice {
        let (ready_invoice, _idem) = match read_invoice_row(&mut conn, &id)? {
            Some(pair) => pair,
            None => continue, // ledger has it but billing row gone — skip silently
        };
        items.push(InvoiceListItem {
            invoice_id: id,
            sequence_number: ready_invoice.sequence_number,
            fiscal_year: ready_invoice.fiscal_year,
            state: trace.derive_state(),
            total_gross: ready_invoice.total_gross().map(|h| h.as_i64()),
        });
    }
    Ok(items)
}

fn get_invoice_detail(state: &AppState, invoice_id: &str) -> Result<Option<InvoiceDetailResponse>> {
    let ledger = Ledger::open(&*state.db_path, state.tenant.clone(), state.binary_hash)
        .context("open audit ledger for serve detail")?;
    let entries = ledger.entries().context("read audit ledger entries")?;

    let mut trace = InvoiceTrace::default();
    let mut audit_entries: Vec<AuditEntryView> = Vec::new();
    let mut found_any = false;
    for entry in &entries {
        if let Some(id) = extract_invoice_id(entry) {
            if id == invoice_id {
                found_any = true;
                trace.merge_entry(entry, invoice_id);
                audit_entries.push(audit_view_of(entry));
            }
        }
    }

    let mut conn = Connection::open(&*state.db_path)
        .with_context(|| format!("open tenant DuckDB at {}", state.db_path.display()))?;
    let billing = read_invoice_row(&mut conn, invoice_id)?;

    if !found_any && billing.is_none() {
        return Ok(None);
    }

    let (sequence_number, fiscal_year, total_gross) = match billing {
        Some((ri, _idem)) => (
            ri.sequence_number,
            ri.fiscal_year,
            ri.total_gross().map(|h| h.as_i64()),
        ),
        None => (0, 0, None),
    };
    Ok(Some(InvoiceDetailResponse {
        invoice_id: invoice_id.to_string(),
        sequence_number,
        fiscal_year,
        state: trace.derive_state(),
        total_gross,
        audit_entries,
    }))
}

fn get_audit_for_invoice(state: &AppState, invoice_id: &str) -> Result<Vec<AuditEntryView>> {
    let ledger = Ledger::open(&*state.db_path, state.tenant.clone(), state.binary_hash)
        .context("open audit ledger for serve audit")?;
    let entries = ledger.entries().context("read audit ledger entries")?;
    let mut out = Vec::new();
    for entry in &entries {
        if let Some(id) = extract_invoice_id(entry) {
            if id == invoice_id {
                out.push(audit_view_of(entry));
            }
        }
    }
    Ok(out)
}

fn audit_view_of(entry: &Entry) -> AuditEntryView {
    AuditEntryView {
        seq: entry.seq.as_u64(),
        kind: format!("{:?}", entry.kind),
        actor: entry.actor.user_id.clone(),
        // ADR-0008 §"Entry shape" names two timestamps: `time_wall`
        // (RFC3339, operator-readable) and `time_mono` (monotonic
        // nanos since process start, drift-immune). The serve view
        // wants the operator-readable form.
        occurred_at: entry.time_wall.to_string(),
    }
}

/// Scoped read tx + billing lookup; returns None if the row is not
/// present.
fn read_invoice_row(
    conn: &mut Connection,
    invoice_id: &str,
) -> Result<Option<(ReadyInvoice, billing::IdempotencyKey)>> {
    let tx = conn
        .transaction()
        .context("begin read transaction for invoice lookup (serve)")?;
    let pair = billing::load_ready_invoice_by_id(&tx, invoice_id)
        .context("billing::load_ready_invoice_by_id (serve)")?;
    tx.commit().context("commit read transaction (serve)")?;
    Ok(pair)
}

// ── State derivation from the audit-ledger trace ─────────────────────

/// Per-invoice accumulator for the audit-ledger walk.
#[derive(Default)]
struct InvoiceTrace {
    has_draft: bool,
    has_submission_response: bool,
    has_retry_requested: bool,
    has_marked_abandoned: bool,
    last_ack_status: Option<String>,
}

impl InvoiceTrace {
    fn merge_entry(&mut self, entry: &Entry, invoice_id: &str) {
        match entry.kind {
            EventKind::InvoiceDraftCreated => self.has_draft = true,
            EventKind::InvoiceSubmissionResponse => {
                if let Ok(parsed) = serde_json::from_slice::<
                    audit_payloads::InvoiceSubmissionResponsePayload,
                >(&entry.payload)
                {
                    if parsed.invoice_id == invoice_id {
                        self.has_submission_response = true;
                    }
                }
            }
            EventKind::InvoiceAckStatus => {
                if let Ok(parsed) = serde_json::from_slice::<audit_payloads::InvoiceAckStatusPayload>(
                    &entry.payload,
                ) {
                    if parsed.invoice_id == invoice_id {
                        self.last_ack_status = Some(parsed.ack_status);
                    }
                }
            }
            EventKind::InvoiceRetryRequested => {
                self.has_retry_requested = true;
            }
            EventKind::InvoiceMarkedAbandoned => {
                self.has_marked_abandoned = true;
            }
            _ => {}
        }
    }

    /// Derive the ADR-0009 §2 typestate label from the accumulated
    /// trace. Order matters: terminal-by-operator (`Abandoned`) wins
    /// over terminal-by-NAV (`Finalized` / `Rejected`); those win
    /// over `Stuck`; `Submitted` is the default once a submission
    /// response exists; otherwise `Ready` (the audit ledger always
    /// records sequence reservation + draft creation for an issued
    /// invoice).
    fn derive_state(&self) -> &'static str {
        if self.has_marked_abandoned {
            return "Abandoned";
        }
        match self.last_ack_status.as_deref() {
            Some("SAVED") => return "Finalized",
            Some("ABORTED") => return "Rejected",
            Some("RECEIVED") | Some("PROCESSING") => {
                // Has an intermediate ack; whether the poll loop ran
                // to exhaustion is not directly knowable from one
                // entry — the serve view labels it `Submitted`. The
                // CLI's `aberp poll-ack` already prints `STUCK`
                // when it terminates with an intermediate ack; the
                // serve view's coarser label is fine for the list.
                return "Submitted";
            }
            _ => {}
        }
        if self.has_submission_response {
            return "Submitted";
        }
        if self.has_draft {
            return "Ready";
        }
        "Unknown"
    }
}

/// Extract the `invoice_id` field (if any) from an audit-ledger entry's
/// typed payload. Returns None for entries that don't carry an
/// invoice_id at all (none of the v3.0 payloads).
fn extract_invoice_id(entry: &Entry) -> Option<String> {
    // All current typed payloads carry an `invoice_id: String` field.
    // We parse permissively — a payload that fails to decode is
    // skipped rather than blowing up the entire serve view.
    #[derive(Deserialize)]
    struct Probe {
        invoice_id: String,
    }
    let probe: Probe = serde_json::from_slice(&entry.payload).ok()?;
    Some(probe.invoice_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constant_time_eq_basic() {
        assert!(constant_time_eq("abcd", "abcd"));
        assert!(!constant_time_eq("abcd", "abce"));
        assert!(!constant_time_eq("abcd", "abc"));
        assert!(!constant_time_eq("", "x"));
        assert!(constant_time_eq("", ""));
    }

    #[test]
    fn derive_state_ladder() {
        let mut t = InvoiceTrace::default();
        assert_eq!(t.derive_state(), "Unknown");
        t.has_draft = true;
        assert_eq!(t.derive_state(), "Ready");
        t.has_submission_response = true;
        assert_eq!(t.derive_state(), "Submitted");
        t.last_ack_status = Some("RECEIVED".to_string());
        assert_eq!(t.derive_state(), "Submitted");
        t.last_ack_status = Some("SAVED".to_string());
        assert_eq!(t.derive_state(), "Finalized");
        t.last_ack_status = Some("ABORTED".to_string());
        assert_eq!(t.derive_state(), "Rejected");
        // Abandoned wins over every NAV terminal.
        t.has_marked_abandoned = true;
        assert_eq!(t.derive_state(), "Abandoned");
    }
}
